package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class MainSceneController {
	@FXML
	private Label userName;
	@FXML
	private TextField userNametxt;
	@FXML
	private Button lgn;
	@FXML
	private TextField passwordtxt;
	@FXML
	private Button rgstr;
	@FXML
	private Label password;

	// Event Listener on Button[#lgn].onAction
	@FXML
	public void loginOkClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#rgstr].onAction
	@FXML
	public void registerOnclicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
