package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class stocksSceneController {
	@FXML
	private MenuItem maskItem;
	@FXML
	private MenuItem vaccineItem;
	@FXML
	private MenuItem testsItem;
	@FXML
	private MenuItem vaccinedItemPatient;
	@FXML
	private MenuItem addnewPatientItem;
	@FXML
	private Button assMaskbtn;
	@FXML
	private Button subMaskbtn;
	@FXML
	private TableView listMasks;
	@FXML
	private TableColumn referencesMaskcolumn;
	@FXML
	private TableColumn typeMaskcolumn;
	@FXML
	private TableColumn quantityMaskcolumn;
	@FXML
	private TextField typeMaskAdd;
	@FXML
	private TextField typeMaskSub;
	@FXML
	private TextField qttMaskAdd;
	@FXML
	private TextField qttMasksub;

	// Event Listener on MenuItem[#maskItem].onAction
	@FXML
	public void maskWindox(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccineItem].onAction
	@FXML
	public void vaccineWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#testsItem].onAction
	@FXML
	public void testsWindows(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccinedItemPatient].onAction
	@FXML
	public void vaccinedPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#addnewPatientItem].onAction
	@FXML
	public void addNewPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#assMaskbtn].onAction
	@FXML
	public void addMask(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#subMaskbtn].onAction
	@FXML
	public void subMask(ActionEvent event) {
		// TODO Autogenerated
	}
}
