package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class TestsSceneController {
	@FXML
	private MenuItem maskItem;
	@FXML
	private MenuItem vaccineItem;
	@FXML
	private MenuItem testsItem;
	@FXML
	private MenuItem vaccinedItemPatient;
	@FXML
	private MenuItem addnewPatientItem;
	@FXML
	private Button addTestsbtn;
	@FXML
	private Button subTestsbtn;
	@FXML
	private TableView listMasks;
	@FXML
	private TableColumn referencesTestscolumn;
	@FXML
	private TableColumn typeTestscolumn;
	@FXML
	private TableColumn quantityTestscolumn;
	@FXML
	private TextField typeTestsAdd;
	@FXML
	private TextField typeTestsSub;
	@FXML
	private TextField qttTestsAdd;
	@FXML
	private TextField qttTestssub;

	// Event Listener on MenuItem[#maskItem].onAction
	@FXML
	public void maskWindox(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccineItem].onAction
	@FXML
	public void vaccineWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#testsItem].onAction
	@FXML
	public void testsWindows(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccinedItemPatient].onAction
	@FXML
	public void vaccinedPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#addnewPatientItem].onAction
	@FXML
	public void addNewPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addTestsbtn].onAction
	@FXML
	public void addTests(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#subTestsbtn].onAction
	@FXML
	public void subTests(ActionEvent event) {
		// TODO Autogenerated
	}
}
