package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class  VaccineSceneController {
	@FXML
	private MenuItem maskItem;
	@FXML
	private MenuItem vaccineItem;
	@FXML
	private MenuItem testsItem;
	@FXML
	private MenuItem vaccinedItemPatient;
	@FXML
	private MenuItem addnewPatientItem;
	@FXML
	private Button addVaccinebtn;
	@FXML
	private Button subVaccinebtn;
	@FXML
	private TableView listMasks;
	@FXML
	private TableColumn referencesVaccinecolumn;
	@FXML
	private TableColumn typeVaccinecolumn;
	@FXML
	private TableColumn quantityVaccinecolumn;
	@FXML
	private TextField typeVaccineAdd;
	@FXML
	private TextField typeVaccineSub;
	@FXML
	private TextField qttVaccineAdd;
	@FXML
	private TextField qttVaccinesub;

	// Event Listener on MenuItem[#maskItem].onAction
	@FXML
	public void maskWindox(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccineItem].onAction
	@FXML
	public void vaccineWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#testsItem].onAction
	@FXML
	public void testsWindows(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccinedItemPatient].onAction
	@FXML
	public void vaccinedPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#addnewPatientItem].onAction
	@FXML
	public void addNewPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addVaccinebtn].onAction
	@FXML
	public void addVaccine(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#subVaccinebtn].onAction
	@FXML
	public void subVaccine(ActionEvent event) {
		// TODO Autogenerated
	}
}
