package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.TableColumn;

public class VaccinedPatientSceneController {
	@FXML
	private MenuItem maskItem;
	@FXML
	private MenuItem vaccineItem;
	@FXML
	private MenuItem testsItem;
	@FXML
	private MenuItem vaccinedItemPatient;
	@FXML
	private MenuItem addnewPatientItem;
	@FXML
	private TableColumn fistNamePatient;
	@FXML
	private TableColumn lastNamePatient;
	@FXML
	private TableColumn nbrSecuPatient;
	@FXML
	private TableColumn DateBirthPatient;
	@FXML
	private TableColumn typeVaccinePatient;
	@FXML
	private TableColumn dateDose1;
	@FXML
	private TableColumn dateDose2;
	@FXML
	private TableColumn dateDose3;

	// Event Listener on MenuItem[#maskItem].onAction
	@FXML
	public void maskWindox(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccineItem].onAction
	@FXML
	public void vaccineWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#testsItem].onAction
	@FXML
	public void testsWindows(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#vaccinedItemPatient].onAction
	@FXML
	public void vaccinedPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#addnewPatientItem].onAction
	@FXML
	public void addNewPatientWindow(ActionEvent event) {
		// TODO Autogenerated
	}
}
